# Use the official Jupyter Notebook base image
FROM jupyter/base-notebook:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install CMake
RUN apt-get update && \
    apt-get install -y cmake

# Install Eigen
RUN apt-get update && \
    apt-get install -y libeigen3-dev

# Install GMP
RUN apt-get update && \
    apt-get install -y libgmp-dev

# Ensure the notebook server is started with the correct user permissions
USER root

# Create a working directory
WORKDIR /home/jovyan/work

# Expose port 8888 for Jupyter Notebook
EXPOSE 8888

# Start Jupyter Notebook
CMD ["start-notebook.sh"]
